### ISSUE TITLE
How to encode heterogeneous JSON array? 

### ISSUE THREAD

**Issue by dboris** [mattjbray/ocaml-decoders#60]
`Decode` has an `uncons` function which makes it possible to decode a JSON value like the following:
```json
["hello", true, 1]
```
What is the opposite operation in Encode? How can this value be encoded given an OCaml tuple of type (string * bool * int)?

**Comment by mattjbray** [comment]
You can write
```ocaml
list value [string "hello"; bool true; int 1]
```

**Comment by dboris** [comment]
Great. Thank you.
